import { Rajdhani } from "next/font/google";
import "./globals.css";

import Header from "@/components/Header";
import Footer from "@/components/Footer";
import CartProvider from "@/components/CartProvider";
import { Toaster } from "@/components/ui/toaster";
import { Analytics } from "@vercel/analytics/react";

const rajdhani = Rajdhani({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-rajdhani",
});

export const metadata = {
  title: "Steamy Shuffle",
  description: "Generated by create next app",
};

const injectGA = () => {
  if (typeof window == "undefined") {
    return;
  }
  window.dataLayer = window.dataLayer || [];
  function gtag() {
    window.dataLayer.push(arguments);
  }
  gtag("js", new Date());

  gtag("config", "YOUR_TRACKING_ID");
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Steamy Shuffle</title>
        <script
          async
          src="https://www.googletagmanager.com/gtag/js?id=YOUR_TRACKING_ID"
        />
        <script>{injectGA()}</script>
      </head>
      <body className={rajdhani.variable}>
        <CartProvider>
          <Header />
          {children}
          <Toaster />
          <Footer />
        </CartProvider>
        <Analytics />
      </body>
    </html>
  );
}
